language: python
python:
  - "3.5"

install: make init
script: make test
after_success:
  - . ./p3_5env/bin/activate
  - coveralls

notifications:
  slack:
    rooms:
      - vt-sailbot:7gOKLogSZkfyIYCRhmupIiUC#boat-programming