language: python
python:
  - "3.5"

services:
  - docker

jobs:
  include:
    - stage: "Tests"
      install: make init
      script: make test
      after_success:
        - . ./p3_5env/bin/activate
        - coveralls
    - stage: "Tests in Beaglebone Black Environment"
      before_install: docker build -t sailbot .
      script: docker run -d sailbot /bin/sh -c "make test"
      if: branch = master

notifications:
  slack:
    rooms:
      - vt-sailbot:7gOKLogSZkfyIYCRhmupIiUC#boat-programming