# Pins must have their function in all caps.
# All pins must include
#   pin_name -- The BBB name of the pin, e.g. "P0_0"
#   pin_type -- The method for reading input from the pin, e.g. ADC
#
# Pin types in this module:
#   - UART
#
# UART:
#  UART pins must specify channel. One of "UART1", "UART2", "UART4" OR "UART5"
#
#
#
#
# WARNING: YAML IS WHITESPACE SENSITIVE! PLEASE MATCH INDENTATION STYLE! This
# means consistently use tabs or spaces, and use the indentation amounts in the
# language spec available here: https://yaml.org/spec/1.2/spec.html


# How frequently the receiver checks for new inputs
read interval: 50 / 1000  # seconds

# Settings to configure for port communication
ports:
  SERIAL:
    # port_name can be found through: 'ls /dev/serial/by-id/'
    # or 'ls /dev/tty*'
    port_name: "/dev/tty01"
    port_type: "Serial"
    baudrate: 4800
    timeout: 0


# The pins connected to channels from the physical receiver
pins:
  UART:
    pin_name: "P0_0"
    pin_type: "UART"
    channel: "UART1"
