pins:
  RUDDER:
    pin_name: "P0_0"
    pin_type: "ADC"
    min_v: .18
    default_v: .26
    max_v: .35
  TRIM:
    pin_name: "P0_0"
    pin_type: "ADC"
    min_v: .18
    default_v: .26
    max_v: .35
  MODE1:
    pin_name: "P0_0"
    pin_type: "GPIO"
    min_v: .18
    max_v: .35
  MODE2:
    pin_name: "P0_0"
    pin_type: "GPIO"
    min_v: .18
    max_v: .35